name: Simple CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your commands
        run: |
          echo "Put your build/test commands here"
          # For example:
          # ./run-tests.sh
